# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2349a9f4e798172bfb542aced48cefc936610ed3797504fc1a0f8d75bdc6ed490f8c66e36e9136b99e062566d458446c711b6446305e7dc423794201c9696ab

test:
  secret_key_base: 5ebb2842814a1632d77f6311c9677f72f941e4a659ba6d423632c98c763af0723823f8db370072a4c3f5dfab5f40019fefbe7a493fd2852a63c508552e7696e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
